### ISSUE TITLE
SqliteDict memory issue

### ISSUE THREAD

**Issue by janrygl** [RaRe-Technologies/sqlitedict#48]
Building LSI model from SqliteDict corpus loads the whole SqliteDict into memory.

How to simulate:

``` python
from sqlitedict import SqliteDict
from gensim.models import TfidfModel, LsiModel
from gensim.models.lsimodel import Projection
from gensim.utils import grouper
from gensim import matutils

s = SqliteDict('documents.sqlite')  # contains namedtuples with field `tokens` containing unicode token tuple
tfidf = TfidfModel.load('tfidf_model.pkl')  # trained on a dictionary built from `s`


class SegmentCorpus(object):
    def __init__(self, storage, built_dictionary):
        self.storage = storage
        self.inner_dictionary = built_dictionary

    def __iter__(self):
        for segment in self.storage.itervalues():
            yield self.inner_dictionary.doc2bow(segment.tokens)


corpus_tfidf = tfidf[SegmentCorpus(s, tfidf.id2word)]
for i in grouper(corpus_tfidf, 5000):
    nnz = sum(len(doc) for doc in i)
    job = matutils.corpus2csc(i, num_docs=len(i), num_nnz=nnz, num_terms=len(tfidf.id2word))
    Projection(len(tfidf.id2word), 100, job, extra_dims=100, power_iters=1)
```

Calling Projection will increase RAM usage to the size of SqliteDict db (in my case 22GB).

**Comment by piskvorky** [comment]
@tmylk add "bug" label.

**Comment by piskvorky** [comment]
@tmylk ping.

@janrygl this is a "feature" that is actually documented: see https://github.com/piskvorky/sqlitedict/blob/master/sqlitedict.py#L457. But really a bug IMO -- goes against sqlitedict's design.

The Projection line was just a red herring -- when you commented it out, the reader (SegmentCorpus iterator) was reading rows off the DB cursor fast enough. With Projection, the cursor was filling up the internal queue faster than your `__iter__` was consuming them, leading to memory problems.

A simple `sleep(1)` statement instead of Projection is enough to slow down reading => cursor rows accumulate inside SqliteDict => memory blows up again.

I'm not sure what "proper" the fix is. We have to be more careful with juggling the output queues between threads, make them somehow blocking if the top-level call is a generator (iterkey, itervalues, iteritems...). It's not going to be trivial, with multiple threads.

As a quick fix, read the (much smaller) keys into memory and avoid the (large) values in memory:

```
class SegmentCorpus(object):
    def __init__(self, storage, built_dictionary):
        self.storage = storage
        self.inner_dictionary = built_dictionary

    def __iter__(self):
        for key in self.storage:  # all keys in memory
            segment = self.storage[key]  # only a single value in memory
            yield self.inner_dictionary.doc2bow(segment.tokens)
```

@tmylk @gojomo thoughts on making this type of iteration the default? It assumes keys are smaller than values, which is a mostly true (values are pickled objects).

**Comment by tmylk** [comment]
@piskvorky Unfortunately only an ower can create new labels. As a collaborator I can only apply existing ones.

**Comment by gojomo** [comment]
Wouldn't adding a `maxsize` at https://github.com/piskvorky/sqlitedict/blob/726d2ca6a56ed2422089ada9834c1c792164b541/sqlitedict.py#L463 force the necessary blocking-before-heap-exhaustion? (Presumably the raw sqlite lib would continue to push in new items as queue-space becomes available.)

The proper limit could start generous (say 10000) but be user-overridable (for cases where the RAM or average value-size or number-of-simultaneous-selects vary).

**Comment by piskvorky** [comment]
If that works that would be great (and easy)!

I looked at queue `maxsize` last night and thought it wouldn't work, but I can't remember why now. I think it should work.

**Comment by piskvorky** [comment]
@tmylk aha, OK. Weird. I created a few labels; let me know if you want any others.
